#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Mar 20 16:42:55 MSK 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 5fc0639649b143d4a44ac19db9ce0e26 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot sim_majority_5_behav xil_defaultlib.sim_majority_5 xil_defaultlib.glbl -log elaborate.log"
xelab -wto 5fc0639649b143d4a44ac19db9ce0e26 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot sim_majority_5_behav xil_defaultlib.sim_majority_5 xil_defaultlib.glbl -log elaborate.log

